### ISSUE TITLE
Doesn't detect client

### ISSUE THREAD

**Issue by guppis** [alextrevisan/HardUO#4]
Hey,
I'm playing in a shard that uses a modified client. I ran HardUO, but it doesn't seem to detect the client. I REALLY want to try this out, can you please contact me? @alextrevisan

**Comment by alextrevisan** [comment]
Hi, it uses uo.dll from EasyUO. Do EasyUO works for you?

**Comment by guppis** [comment]
Easy UO is banned here. We use g-defender. I can send all the files to you
too look

**Comment by guppis** [comment]
The shard is : http://elysiumuo.com/index.php

It uses client 203 (modified)

Basically you install a fresh uo install and the connector in seperate
folders, then config the connector so it knows where the main UO folder is
and run the connector (not the client.exe) maybye that's why it doesn't
read?

**Comment by alextrevisan** [comment]
It's a public shard? Please, send me the links and I'll test it

**Comment by guppis** [comment]
Yes, this is a public shard.

The launcher: http://elysium.uolist.net/updt/elysium_setup.rar

The uo install: http://178.33.71.61/UOML_setup.exe

Basically you have a fresh uo install and install the launcher in another
folder. Set up the launcher so it knows where the main UO folder is and
launch elysium.exe

It firstly turns on some 3rd party program, and then goes into client

**Comment by alextrevisan** [comment]
ah ok, i'll try later

**Comment by guppis** [comment]
Thank you very much!

If you have any questions, I'm here to help.

This shard is quite interesting, but since they have disabled almost all
3rd party programs, it's too much of a grind.

**Comment by alextrevisan** [comment]
Hi! Sorry, but after some tests i figured out that it can't be done in a simple way, since it detects UO executable and depends on specific memory regions to work. This shards uses a custom executable making it a totally diferent thing. It can be done in other ways, using something like "man in the middle" but the work to make this is huge... open to sugestions =)
